### ISSUE TITLE
npm install npm ERR! cb() never called!

### ISSUE THREAD

**Issue by MarFelix** [NorthwoodsSoftware/gojs-angular-video-sample#8]
![image](https://user-images.githubusercontent.com/25601986/110020573-5b8e1c00-7cef-11eb-9d6f-caad4ddc8055.png)
![image](https://user-images.githubusercontent.com/25601986/110020694-7c567180-7cef-11eb-99e2-c1791932d023.png)
![image](https://user-images.githubusercontent.com/25601986/110020863-af006a00-7cef-11eb-92e9-10423a450f1e.png)

**Comment by rjohnson465** [comment]
Hello,

I just tried installing and running this project with Node version 12.16.3 and npm version 6.14.4 and had no issue. A quick Google search of your error message turns up dozens of possible results, so I'm not sure what's wrong.

However, I would recommend instead, you make use of our GoJS/Angular components we publish in gojs-angular. 
GitHub: https://github.com/NorthwoodsSoftware/gojs-angular
NPM: https://www.npmjs.com/package/gojs-angular
More Info: https://gojs.net/latest/intro/angular.html
An example using gojs-angular: https://github.com/NorthwoodsSoftware/gojs-angular-basic
